import "./globals.css";
// NextAuthProviders
import NextAuthProviders from "@/Providers/NextAuthProviders";
// Font
import { estedad } from "@/utils/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={estedad.className}>
        <NextAuthProviders>{children}</NextAuthProviders>
      </body>
    </html>
  );
}
